version: "3.8"

services:
  app:
    build: .
    container_name: app_container
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/usr/app
    depends_on:
      - database
    network_mode: "bridge"

  database:
    image: ${DB_TYPE}:${DB_VERSION}
    container_name: database_container
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/data/postgres
    network_mode: "bridge"

volumes:
  pgdata:
    driver: local
