version: "3.7"

services:
  app:
    build: .
    container_name: app_container
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/app
    depends_on:
      - database
    network_mode: "host"

  database:
    image: ${DB_TYPE}
    container_name: database_container
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
    network_mode: "host"

volumes:
  pgdata:
    driver: local
