version: "3.7"

services:
  app:
    build: .
    container_name: app_container
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/app
    depends_on:
      - database
    network_mode: "host"

